// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3e1WiDfpkjpWu1M7YTROrU488soVj2GA',
    appId: '1:261509754673:web:c375eacda0ed3d79534a10',
    messagingSenderId: '261509754673',
    projectId: 'student-smart-quiz',
    authDomain: 'student-smart-quiz.firebaseapp.com',
    storageBucket: 'student-smart-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHQ0NzXDdDu-6ZvkKgDN7B1U8OI4M2kc',
    appId: '1:261509754673:android:3142df2430fa5f62534a10',
    messagingSenderId: '261509754673',
    projectId: 'student-smart-quiz',
    storageBucket: 'student-smart-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Vi5zg7TjTPKdfDziqtnSfDDAB1ZhgWE',
    appId: '1:261509754673:ios:13eb138d2cff7722534a10',
    messagingSenderId: '261509754673',
    projectId: 'student-smart-quiz',
    storageBucket: 'student-smart-quiz.firebasestorage.app',
    iosBundleId: 'com.example.smartQuiz',
  );
}
